/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"

float *
calculadora_1_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	int opcion=argp->opcion;
	switch(opcion){
	case 1:
		result=argp->a+argp->b;
		break;
	case 2:
		result=argp->a-argp->b;
		break;
	case 3:
		result=argp->a*argp->b;
		break;
	case 4:
		result=argp->a/argp->b;
		break;
	default:
		printf("Opcion equivocada\n");
	}

	return &result;
}
