/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"


void
calculadora_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	valores  calculadora_1_arg;
	
	printf("Selecciona una opcion\n");
	printf("[1] Suma (a+b)\n");
	printf("[2] Resta (a-b)\n");
	printf("[3] Multiplicacion (a*b)\n");
	printf("[4] Division (a/b)\n");
	scanf("%f", &calculadora_1_arg.opcion);

	printf("Escribe el valor de a: ");
	scanf("%f", &calculadora_1_arg.a);
	printf("Escribe el valor de b: ");
	scanf("%f", &calculadora_1_arg.b);

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculadora_1(&calculadora_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("El resultado de la operacion es: %f\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_prog_1 (host);
exit (0);
}
